---
port: 3000
horoscope-services:
  horoscope-api-herokuapp-com:
    apiurl: "http://horoscope-api.herokuapp.com/horoscope"
    dailyEndpoint: "today"
    weeklyEndpoint: "week"

  babi-hefesto-io:
    apiurl: "http://babi.hefesto.io/signo"
    dailyEndpoint: "dia"
    weeklyEndpoint: "semana"
redis:
  host: "192.168.1.122"
  port: 6379